config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users do
    resources :meetings
  end
  resources :rooms do
    resources :meetings do
      resources :comments
    end
  end

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  @user = User.first
  user = current_user
  @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :fav_color, :dob, :phone)
  end
end

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
    <h1>Schedule Your Conference Room Today!</h1>

    <p>Welcome to The Iron Yard's conference scheduler app! Here at The Iron Yard we have 8 beautiful rooms available for our users to reserve for their conferences and meetings. In order to reserve a conference room and schedule a meeting you need to have an account and be signed in, so if you don't already have an account, sign up now!</p>

    <% if user_signed_in? %>
      <div class="alert alert-dismissible alert-success">
      <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "btn btn-primary btn-lg" ) %>
      <%= link_to('Users', users_path, class: "btn btn-primary btn-lg") %>
      <%= link_to('Conference Rooms',rooms_path, class: "btn btn-primary btn-lg") %>
      </div>
    <% else %>
      <div class="alert alert-dismissible alert-warning">
        <h4>Please Sign In or Sign Up to access the site!</h4>
      </div>
      <div class="alert alert-dismissible alert-danger">
        <%= link_to('Sign Up Now', new_user_registration_path, class: "btn btn-primary btn-lg")%>
        <%= link_to('Sign In Now', new_user_session_path, class: "btn btn-primary btn-lg")%>
      </div>
    <% end %>
  </div>
  <div class="col-md-2">
  </div>
</div>