config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users do
    resources :meetings
  end
  resources :rooms do
    resources :meetings do
      resources :comments
    end
  end

  root 'welcome#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :meetings
  accepts_nested_attributes_for :meetings

  validates_presence_of :room_name, :location
  paginates_per 5
  has_attached_file :photo,
  :styles => { :medium => "300x300>", :thumb => "100x100>" },
  :bucket => 'kbjsinstaclone',
  :url =>':s3_domain_url',
  :path => ':class/:attachment/:id_partition/:style/:filename',
  :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    user = current_user
    @users = User.all
    @rooms = Room.all.page params[:page]
    @room = Room.new
  end

  def show
    @room = Room.find(params[:id])
    # @meeting = Meeting.find(params[:id])
    # @comment.meeting_id = @meeting.id
    # user = User.find(params[user.id])
    #@meeting = @room.meetings.new
  end

  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'User was successfully created.' }
        format.json { render json: @room, status: :created, location: @room }
      else
        format.html { render "welcome/index" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
    end

  private
  def room_params
    params.require(:room).permit(:room_name, :location, :description, :photo,
                                 :meetings_attributes => [:user_id, :room_id, :start_time, :end_time, :title]
                                 )
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_meeting_scheduler.html.erb
<%= simple_form_for([@room, Meeting.new]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, label: 'Meeting name must be between 4 and 50 characters' %>
    <p>Start Time</p>
    <%= f.datetime_select :start_time, label: "Start Time"%>
    <br />
    <br />
    <p>End Time</p>
    <%= f.datetime_select :end_time%>
  </div>
  <br />

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-warning btn-sm" %>
  </div>

<% end %>

app/views/rooms/_room_form.html.erb
<%= simple_form_for @room do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :room_name %>
    <%= f.input :location %>
    <%= f.input :description %>
    <%= f.input :photo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-2">

  </div>

  <div class="col-md-8">
    <div class="well well-lg">
      <h2 style="text-align: center">Our Conference Rooms</h2>
    </div>
      <% @rooms.each do |room| %>
      <ul>
        <li class="room-info"><h3><%= link_to room.room_name, room_path(room) %></h3></li>
        <li class="room-info"><%= image_tag room.photo.url(:medium) %></li>
        <li class="room-info">Location: <%= room.location %></li>
        <li class="room-info">Description: <%= room.description %></li>
      </ul>
      <hr />
          <% end %>
      <%= paginate @rooms %><br />
      <%= page_entries_info @rooms %>
  </div>
  <div class="col-md-2">
  </div>
</div>

app/views/rooms/show.html.erb
<h1 style="text-align: center"><%= @room.room_name %></h1>
<hr />
<div class="row">
  <div class="col-md-6">
    <div class="well">

    <div class="room-show-pic"><%= image_tag @room.photo.url(:medium) %></div>
    <br />

    <div class="list-group">
      <li class="list-group-item active"><%= @room.room_name %></li>
      <li class="list-group-item active">Location: <%= @room.location %></li>
      <li class="list-group-item active"><%= @room.description %></li>
    </div>

    </div>
  </div>
  <div class="col-md-1">
  </div>
  <div class="col-md-5">
    <h3>Schedule a meeting for the <%= @room.room_name %></h3>
    <%= render 'meeting_scheduler' %>
  </div>
</div>

<hr />

<h1>Meetings Scheduled for <%= @room.room_name %></h1>
<table id='meetings-table' class='table table-striped'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Scheduler</th>
      <th>Comment</th>

    </tr>
  </thead>

  <tbody>
  <% @room.meetings.each do |meeting| %>
    <tr>
      <td><%= meeting.title %></td>
      <td><time><%= meeting.start_time %></time></td>
      <td><time><%= meeting.end_time %></time></td>
      <td><%= link_to meeting.user.full_name, user_path(meeting.user) %></td>
      <td><%= link_to('Leave a Comment', new_room_meeting_comment_path(meeting.room, meeting), class: "btn btn-primary btn-sm") %></td>

    </tr>
  <% end %>
  </tbody>
</table>